### ISSUE TITLE
ability to add progress bars

### ISSUE THREAD

**Issue by skeenan** [niyue/skillmap#1]
This looks great. Would love to also be able to add progress bars as in the original WASM diagram.

**Comment by niyue** [comment]
Thanks so much for the suggestion. This was my initial plan as well. But when it comes to implementation, I decided to use mermaid as the charting tool since it has some benefits I want e.g. text based/github embeddable/editor support. Everything can be done with mermaid effortlessly except this progress bar. 

I use flowchart in mermaid to model this diagram, but there seems no element in flowchart that can be controlled precisely like the progress bar in the mozilla blog. 

So I chose a different way to represent the progress bar currently. Each skill can be set with a status, and three values are allowed: [new|beingLeanred|learned]. Once set, each skill (and the skill group containing it) will be rendered with a different color (new ==> grey, beingLearned ==> light color, leanred ==> dark color). 

This is less ideal but it is the only solution I found. Let me know if you have any other idea for it. Thanks.

**Comment by niyue** [comment]
I add the support in the new release (0.3.0)

You can now specify different styles of progress bar like this:
```
[skillmap]
name = "url shortener"
icon = "hashtag"
# theme = "pale"
# orientation = "LR"
progress_bar_style = 17  #<=== see here
```

You can specify the progress for a skill like this:
```
[groups.webui]
name = "web ui"
icon = "desktop"
    [groups.webui.skills.url_validator]
    name = "url validator"
    icon = "globe"
    requires = ["groups.webui.skills.react"]
    progress = "0/3" #<=== see here
    [groups.webui.skills.react]
    name = "react"
    icon = "list"
    status = "beingLearned"
    progress = "1/3" #<=== see here
```

There are 28 different styles of progress bars added, and you can pick the one you like by specifying a value for the `progress_bar_style` property of the skillmap.

Here are some exmaples:

This is the default style:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/27754/156275286-e7412a23-9483-464b-b1a5-d6c044f20c41.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/27754/156275539-829bfb11-7b16-43ea-b958-995bbbbdda82.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/27754/156275563-1dca4d8c-cbcd-4d88-ba03-70fcd992717a.png">


Some are based on emoji:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/27754/156275088-2be49fe9-9de3-46f1-a415-cb956efc7a30.png">

<img width="615" alt="image" src="https://user-images.githubusercontent.com/27754/156275402-306e2822-f119-4567-83d9-52e102c96809.png">


<img width="611" alt="image" src="https://user-images.githubusercontent.com/27754/156275206-931ff0fa-7643-477b-9d96-1af43536286f.png">

**Comment by niyue** [comment]
@skeenan thanks for submitting the issue, and that motivates me to get this addressed. The progress bar lay out is still very basic, just a horizontal bar, but I think it could serve the purpose in most cases. 

I merged the PR (https://github.com/niyue/skillmap/pull/2) and released a new version of the package in PyPi (https://pypi.org/project/skillmap), and you can download it and give it a try, and let me know if it helps.
